##### NumPy’s main object is the homogeneous multidimensional array.
##### NumPy dimensions are called axes.
##### NumPy’s array class is called ndarray. It is also known by the alias array.


###### ndarray.ndim the number of axes (dimensions) of the array.
###### ndarray.shape the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
###### ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.
###### ndarray.dtype an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
###### ndarray.itemsize the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to
###### ndarray.dtype.itemsize.
###### ndarray.data the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape


(3, 5)

In [5]:
a.size

15

In [6]:
a.ndim

2

In [7]:
a.dtype

dtype('int64')

In [8]:
a.itemsize

8

In [9]:
a.data

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])


In [12]:
b

array([6, 7, 8])

In [13]:
 type(b)


numpy.ndarray

In [14]:
 a = np.array([2,3,4])

In [15]:
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b = np.array([1.2, 3.5, 5.1])

In [18]:
b

array([1.2, 3.5, 5.1])

In [19]:
b.dtype

dtype('float64')

In [20]:
 b = np.array([(1.5,2,3), (4,5,6)])

In [21]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
b.dtype

dtype('float64')

In [23]:
 c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [24]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

##### Default

In [25]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((3,4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [27]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Ones 

##### Default

In [28]:
np.ones( (2,3,4) ) 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
np.empty( (2,3) ) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
np.empty( (2,3), dtype=np.int8 ) 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [31]:
np.arange( 10, 30, 5 ) # 10 is start, 30 is End and 5 is increament

array([10, 15, 20, 25])

In [32]:
np.arange( 0, 2, 0.3 ) # 0 is the start 2 is the End and 0.3 is increament

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [33]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
np.linspace( 0, 2*pi, 100 )

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [35]:
pi

3.141592653589793

In [36]:
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)

In [37]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [38]:
a = np.arange(6) 

In [39]:
a

array([0, 1, 2, 3, 4, 5])

In [40]:
print(a)

[0 1 2 3 4 5]


In [41]:
a = np.arange(12).reshape(4,3) 

In [42]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
 c = np.arange(24).reshape(2,3,4) 

In [44]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [46]:
print(np.arange(10000))


[   0    1    2 ... 9997 9998 9999]


In [47]:
 print(np.arange(10000).reshape(100,100))


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [48]:
import sys


In [49]:
np.set_printoptions(threshold=sys.maxsize)

In [50]:
sys.maxsize

9223372036854775807

In [51]:
a = np.array( [20,30,40,50] )

In [52]:
b = np.arange( 4 )

In [53]:
b

array([0, 1, 2, 3])

In [54]:
a

array([20, 30, 40, 50])

In [55]:
a-b

array([20, 29, 38, 47])

In [56]:
b**2

array([0, 1, 4, 9])

In [57]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [58]:
a<35

array([ True,  True, False, False])

In [59]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )


In [60]:
A*B

array([[2, 0],
       [0, 4]])

In [61]:
A@B

array([[5, 4],
       [3, 4]])

In [62]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [63]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))


In [64]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [65]:
b

array([[0.73967088, 0.95181898, 0.97203614],
       [0.54473967, 0.04595736, 0.0698568 ]])

In [66]:
a*=3

In [67]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [68]:
b+=a

In [69]:
b

array([[3.73967088, 3.95181898, 3.97203614],
       [3.54473967, 3.04595736, 3.0698568 ]])

In [70]:
a = np.ones(3, dtype=np.int32)

In [71]:
a

array([1, 1, 1], dtype=int32)

In [72]:
b = np.linspace(0,pi,3)

In [73]:
b

array([0.        , 1.57079633, 3.14159265])

In [74]:
b.dtype.name

'float64'

In [75]:
c =a+b

In [76]:
c

array([1.        , 2.57079633, 4.14159265])

In [77]:
d = np.exp(c*1j)

In [78]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [79]:
d.dtype.name

'complex128'

In [80]:
a = np.random.random((2,3))

In [81]:
a

array([[0.26879089, 0.91023052, 0.5213633 ],
       [0.3613351 , 0.80449791, 0.06234216]])

In [82]:
a.sum()

np.float64(2.9285598678917726)

In [83]:
a.min()

np.float64(0.062342161060974566)

In [84]:
a.max()

np.float64(0.910230515725422)

In [85]:
 b = np.arange(12).reshape(3,4)


In [86]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
 b.sum(axis=0) 

array([12, 15, 18, 21])

In [88]:
 b.sum(axis=1) 

array([ 6, 22, 38])

In [89]:
b.min(axis=0)

array([0, 1, 2, 3])

In [90]:
b.min(axis=1)

array([0, 4, 8])

In [91]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [92]:
B = np.arange(3)


In [93]:
B

array([0, 1, 2])

In [94]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [95]:
np.sqrt(B)


array([0.        , 1.        , 1.41421356])

In [96]:
C = np.array([2., -1., 4.])

In [97]:
np.add(B, C)


array([2., 0., 6.])

In [98]:
a = np.arange(10)**3

In [99]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [100]:
a[2]

np.int64(8)

In [101]:
a[2:5]

array([ 8, 27, 64])

In [102]:
a[:6:2]

array([ 0,  8, 64])

In [103]:
a[:6:2] = -1000

In [104]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [105]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [106]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/var/folders/sf/59w_hmrx1cj494_xzfjzj6q80000gn/T/ipykernel_84636/2421933163.py:2: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [107]:
def f(x,y):
    return 100*x+y

In [108]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[  0,   1,   2,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203],
       [300, 301, 302, 303],
       [400, 401, 402, 403]])

In [109]:
b[:, 1] # column 2

array([  1, 101, 201, 301, 401])

In [110]:
b[1:3, :]

array([[100, 101, 102, 103],
       [200, 201, 202, 203]])

In [111]:
b[-1]

array([400, 401, 402, 403])

In [112]:
b[:,-1]

array([  3, 103, 203, 303, 403])

In [113]:
c = np.array( [[[ 0, 1, 2], # a 3D array (two stacked 2D arrays)
... [ 10, 12, 13]],
... [[100,101,102],
... [110,112,113]]])


In [114]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [115]:
c.shape

(2, 2, 3)

In [116]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [117]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [118]:
 for row in b:
     print(row)


[0 1 2 3]
[100 101 102 103]
[200 201 202 203]
[300 301 302 303]
[400 401 402 403]


In [119]:
for element in b.flat:
    print(element)


0
1
2
3
100
101
102
103
200
201
202
203
300
301
302
303
400
401
402
403


In [120]:
print(b.flat)

In [121]:
b

array([[  0,   1,   2,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203],
       [300, 301, 302, 303],
       [400, 401, 402, 403]])

In [122]:
a = np.floor(10*np.random.random((3,4)))

In [123]:
a

array([[2., 3., 2., 1.],
       [3., 1., 0., 4.],
       [4., 7., 8., 4.]])

In [124]:
a.shape

(3, 4)

In [125]:
 a.ravel()

array([2., 3., 2., 1., 3., 1., 0., 4., 4., 7., 8., 4.])

In [126]:
a.reshape(6,2)

array([[2., 3.],
       [2., 1.],
       [3., 1.],
       [0., 4.],
       [4., 7.],
       [8., 4.]])

In [127]:
a.T

array([[2., 3., 4.],
       [3., 1., 7.],
       [2., 0., 8.],
       [1., 4., 4.]])

In [128]:
a.T.shape

(4, 3)

In [129]:
a.shape

(3, 4)

In [130]:
a

array([[2., 3., 2., 1.],
       [3., 1., 0., 4.],
       [4., 7., 8., 4.]])

In [131]:
a.resize((2,6))

In [132]:
a

array([[2., 3., 2., 1., 3., 1.],
       [0., 4., 4., 7., 8., 4.]])

In [133]:
a.reshape(2,6)

array([[2., 3., 2., 1., 3., 1.],
       [0., 4., 4., 7., 8., 4.]])

In [134]:
a.reshape(3,-1)

array([[2., 3., 2., 1.],
       [3., 1., 0., 4.],
       [4., 7., 8., 4.]])

In [135]:
a = np.floor(10*np.random.random((2,2)))

In [136]:
a

array([[0., 7.],
       [7., 1.]])

In [137]:
b = np.floor(10*np.random.random((2,2)))

In [138]:
b

array([[4., 7.],
       [2., 7.]])

In [139]:
np.vstack((a,b))

array([[0., 7.],
       [7., 1.],
       [4., 7.],
       [2., 7.]])

In [140]:
np.hstack((a,b))

array([[0., 7., 4., 7.],
       [7., 1., 2., 7.]])

In [141]:
from numpy import newaxis

In [142]:
np.column_stack((a,b))

array([[0., 7., 4., 7.],
       [7., 1., 2., 7.]])

In [143]:
a = np.array([4.,2.])


In [144]:
b = np.array([3.,8.])


In [145]:
a

array([4., 2.])

In [146]:
b

array([3., 8.])

In [147]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [148]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [149]:
a[:,newaxis] 

array([[4.],
       [2.]])

In [150]:
np.column_stack((a[:,newaxis],b[:,newaxis]))


array([[4., 3.],
       [2., 8.]])

In [151]:
 np.hstack((a[:,newaxis],b[:,newaxis])) #

array([[4., 3.],
       [2., 8.]])

In [152]:
 np.r_[1:4,0,4]


array([1, 2, 3, 0, 4])

In [153]:
np.c_[1:4]

array([[1],
       [2],
       [3]])

In [154]:
 a = np.floor(10*np.random.random((2,12)))


In [155]:
a

array([[9., 5., 7., 7., 4., 9., 4., 1., 8., 0., 5., 8.],
       [1., 7., 6., 4., 4., 9., 6., 0., 9., 5., 5., 7.]])

In [156]:
np.hsplit(a,4) 

[array([[9., 5., 7.],
        [1., 7., 6.]]),
 array([[7., 4., 9.],
        [4., 4., 9.]]),
 array([[4., 1., 8.],
        [6., 0., 9.]]),
 array([[0., 5., 8.],
        [5., 5., 7.]])]

In [157]:
np.hsplit(a,(3,4)) 

[array([[9., 5., 7.],
        [1., 7., 6.]]),
 array([[7.],
        [4.]]),
 array([[4., 9., 4., 1., 8., 0., 5., 8.],
        [4., 9., 6., 0., 9., 5., 5., 7.]])]

In [158]:
 a = np.arange(12)


In [159]:
b = a

In [160]:
a is b

True

In [161]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [162]:
a=b

In [163]:
a ==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [164]:
id(a)

4589643792

In [165]:
id(b)

4589643792

In [166]:
b.shape = 3,4

In [167]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
print(a.base)

None


In [171]:
 c = a.view()

In [172]:
c is a

False

In [173]:
c.base is a

True

In [174]:
a.flags.owndata

True

In [175]:
c.flags.owndata

False

In [176]:
 c.shape = 2,6

In [177]:
a.shape

(3, 4)

In [178]:
c.shape

(2, 6)

In [179]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [180]:
 c[0,4] = 1234 

In [181]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [182]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [183]:
 s = a[ : , 1:3] 

In [184]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [185]:
s[:] = 10

In [186]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [187]:
c

array([[   0,   10,   10,    3, 1234,   10],
       [  10,    7,    8,   10,   10,   11]])

In [188]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [189]:
d = a.copy()

In [190]:
d

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [191]:
a is d

False

In [192]:
d.base is a

False

In [193]:
 d[0,0] = 9999

In [194]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [195]:
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [196]:
 a = np.arange(int(1e8))

In [197]:
b = a[:100].copy()

In [198]:
 del a

In [199]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [200]:
a = np.arange(12)**2

In [201]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [202]:
i = np.array( [ 1,1,3,8,5 ] )

In [203]:
a[i]

array([ 1,  1,  9, 64, 25])

In [204]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )

In [205]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [206]:
palette = np.array( [ [0,0,0], # black
... [255,0,0], # red
... [0,255,0], # green
... [0,0,255], # blue
... [255,255,255] ] ) 

In [207]:
image = np.array( [ [ 0, 1, 2, 0 ], [ 0, 3, 4, 0 ] ] )

In [208]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [209]:
a = np.arange(12).reshape(3,4)


In [210]:
 a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
i = np.array( [ [0,1], # indices for the first dim of a
... [1,2] ] )

In [212]:
i

array([[0, 1],
       [1, 2]])

In [213]:
j = np.array( [ [2,1], # indices for the second dim
... [3,3] ] )


In [214]:
j

array([[2, 1],
       [3, 3]])

In [215]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [216]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [218]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [219]:
 l = [i,j]

In [220]:
l

[array([[0, 1],
        [1, 2]]),
 array([[2, 1],
        [3, 3]])]