##### NumPy’s main object is the homogeneous multidimensional array.
##### NumPy dimensions are called axes.
##### NumPy’s array class is called ndarray. It is also known by the alias array.


###### ndarray.ndim the number of axes (dimensions) of the array.
###### ndarray.shape the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
###### ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.
###### ndarray.dtype an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
###### ndarray.itemsize the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to
###### ndarray.dtype.itemsize.
###### ndarray.data the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape


(3, 5)

In [6]:
a.size

15

In [7]:
a.ndim

2

In [8]:
a.dtype

dtype('int64')

In [9]:
a.itemsize

8

In [10]:
a.data

In [11]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6, 7, 8])


In [13]:
b

array([6, 7, 8])

In [14]:
 type(b)


numpy.ndarray

In [16]:
 a = np.array([2,3,4])

In [17]:
a

array([2, 3, 4])

In [18]:
a.dtype

dtype('int64')

In [19]:
b = np.array([1.2, 3.5, 5.1])

In [20]:
b

array([1.2, 3.5, 5.1])

In [21]:
b.dtype

dtype('float64')

In [22]:
 b = np.array([(1.5,2,3), (4,5,6)])

In [23]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [24]:
b.dtype

dtype('float64')

In [25]:
 c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [26]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

##### Default

In [27]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros((3,4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [28]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Ones 

##### Default

In [29]:
np.ones( (2,3,4) ) 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
np.empty( (2,3) ) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
np.empty( (2,3), dtype=np.int8 ) 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [34]:
np.arange( 10, 30, 5 ) # 10 is start, 30 is End and 5 is increament

array([10, 15, 20, 25])

In [35]:
np.arange( 0, 2, 0.3 ) # 0 is the start 2 is the End and 0.3 is increament

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [36]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
np.linspace( 0, 2*pi, 100 )

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [38]:
pi

3.141592653589793

In [39]:
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)

In [40]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [41]:
a = np.arange(6) 

In [42]:
a

array([0, 1, 2, 3, 4, 5])

In [43]:
print(a)

[0 1 2 3 4 5]


In [44]:
a = np.arange(12).reshape(4,3) 

In [45]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
 c = np.arange(24).reshape(2,3,4) 

In [47]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
